FROM grafana/grafana:11.1.4

ARG GF_UID=1000

USER root
RUN echo http://dl-2.alpinelinux.org/alpine/edge/community/ >> /etc/apk/repositories && \
    apk --no-cache add shadow && \
    usermod --uid $GF_UID grafana; \
    chown -R grafana /etc/grafana

COPY --chown=grafana grafana/ /etc/grafana/provisioning/

USER grafana