---

apiVersion: 1

# see: https://github.com/domainaware/parsedmarc/blob/master/parsedmarc/opensearch.py
datasources:
  - orgId: 1
    name: 'DMARC-Aggregate'
    type: 'grafana-opensearch-datasource'
    access: 'proxy'
    url: 'http://opensearch:9200'
    database: '[dmarc_aggregate-]YYYY-MM-DD'
    editable: true
    jsonData:
      timeField: 'date_begin'
      interval: 'Daily'
      version: '2.16.0'
      flavor: 'opensearch'

  - orgId: 1
    name: 'DMARC-Forensic'
    type: 'grafana-opensearch-datasource'
    access: 'proxy'
    url: 'http://opensearch:9200'
    database: '[dmarc_forensic-]YYYY-MM-DD'
    editable: true
    jsonData:
      timeField: 'arrival_date'
      interval: 'Daily'
      version: '2.16.0'
      flavor: 'opensearch'

  - orgId: 1
    name: 'DMARC-TLS'
    type: 'grafana-opensearch-datasource'
    access: 'proxy'
    url: 'http://opensearch:9200'
    database: '[smtp_tls-]YYYY-MM-DD'
    editable: true
    jsonData:
      timeField: 'date_begin'
      interval: 'Daily'
      version: '2.16.0'
      flavor: 'opensearch'
